x = -2:0.1:2;
y = -1:0.1:2;
[x_grid, y_grid] = meshgrid(x,y);
z= 1./(1 + x_grid.^2 + y_grid.^2);
subplot(2,1,1), surf(x_grid, y_grid,z),...
  title('Gráfica de malla'), xlabel('x'),...
  ylabel('y'), zlabel('z'), pause
subplot(2,1,1), surf(x_grid, y_grid, z),...
  title('Gráfica de superficie'), xlabel('x'),...
  ylabel('y'), zlabel('z')
